export enum AuditEntityType {
  USER = 'USER',
  PROJECT = 'PROJECT',
  TICKET = 'TICKET',
  COMMENT = 'COMMENT',
  TICKET_DEPENDENCY = 'TICKET_DEPENDENCY',
  TICKET_ATTACHMENT = 'TICKET_ATTACHMENT',
}
